from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.units import inch, cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from io import BytesIO
import hashlib
from datetime import datetime, timezone
from pathlib import Path
import logging

logger = logging.getLogger(__name__)

BRAND_BLUE = colors.HexColor('#3B82F6')
BRAND_DARK = colors.HexColor('#0B1220')
BRAND_SURFACE = colors.HexColor('#111827')
TEXT_WHITE = colors.HexColor('#F9FAFB')
TEXT_MUTED = colors.HexColor('#9CA3AF')
SUCCESS_GREEN = colors.HexColor('#10B981')
DANGER_RED = colors.HexColor('#EF4444')
WARNING_AMBER = colors.HexColor('#F59E0B')


def get_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='DPDPTitle', parent=styles['Heading1'], fontSize=20, spaceAfter=12, textColor=BRAND_BLUE, fontName='Helvetica-Bold'))
    styles.add(ParagraphStyle(name='DPDPSubtitle', parent=styles['Normal'], fontSize=12, spaceAfter=8, textColor=colors.HexColor('#6B7280')))
    styles.add(ParagraphStyle(name='DPDPBody', parent=styles['Normal'], fontSize=10, spaceAfter=6, leading=14))
    styles.add(ParagraphStyle(name='DPDPLabel', parent=styles['Normal'], fontSize=9, textColor=colors.HexColor('#6B7280'), spaceAfter=2))
    styles.add(ParagraphStyle(name='DPDPFooter', parent=styles['Normal'], fontSize=8, textColor=colors.HexColor('#9CA3AF'), alignment=TA_CENTER))
    return styles


def build_header(styles, title, subtitle=""):
    elements = []
    elements.append(Paragraph("DPDP SHIELD", styles['DPDPSubtitle']))
    elements.append(Paragraph(title, styles['DPDPTitle']))
    if subtitle:
        elements.append(Paragraph(subtitle, styles['DPDPSubtitle']))
    elements.append(HRFlowable(width="100%", thickness=1, color=BRAND_BLUE, spaceAfter=12))
    elements.append(Spacer(1, 12))
    return elements


def build_footer(styles):
    elements = []
    elements.append(Spacer(1, 24))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#374151'), spaceAfter=8))
    elements.append(Paragraph(f"Generated by DPDP Shield | {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}", styles['DPDPFooter']))
    elements.append(Paragraph("Prevent | Detect | Respond", styles['DPDPFooter']))
    return elements


def build_info_table(data_pairs, styles):
    table_data = []
    for label, value in data_pairs:
        table_data.append([Paragraph(f"<b>{label}:</b>", styles['DPDPBody']), Paragraph(str(value), styles['DPDPBody'])])
    t = Table(table_data, colWidths=[2.5*inch, 4*inch])
    t.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('TOPPADDING', (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ('LINEBELOW', (0,0), (-1,-1), 0.5, colors.HexColor('#E5E7EB')),
    ]))
    return t


class PDFService:
    def __init__(self, output_dir):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.styles = get_styles()

    def _generate(self, filename, build_func):
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1*cm, bottomMargin=1*cm, leftMargin=2*cm, rightMargin=2*cm)
        story = build_func(self.styles)
        doc.build(story)
        pdf_bytes = buffer.getvalue()
        sha256 = hashlib.sha256(pdf_bytes).hexdigest()
        filepath = self.output_dir / filename
        with open(filepath, 'wb') as f:
            f.write(pdf_bytes)
        return pdf_bytes, sha256, filename

    def generate_dpb_notice(self, incident):
        filename = f"dpb_notice_{incident.get('incident_id','')}.pdf"
        def build(styles):
            story = build_header(styles, "DATA PROTECTION BOARD NOTICE", "Under Section 8(6) of the Digital Personal Data Protection Act, 2023")
            story.append(build_info_table([
                ("Incident ID", incident.get('incident_id', 'N/A')),
                ("Date of Discovery", incident.get('discovery_time', 'N/A')),
                ("Nature of Breach", incident.get('nature', 'Unauthorized access to personal data')),
                ("Systems Impacted", incident.get('systems', 'Customer Database')),
                ("Data Categories", incident.get('categories', 'Name, Email, Phone')),
                ("Estimated Affected Users", incident.get('affected_count', 'N/A')),
                ("Containment Status", incident.get('containment_status', 'Contained')),
                ("Remedial Actions", incident.get('remedial', 'Access revoked, passwords reset, audit initiated')),
            ], styles))
            story.append(Spacer(1, 16))
            story.append(Paragraph("<b>Description of Breach:</b>", styles['DPDPBody']))
            story.append(Paragraph(incident.get('description', 'A security breach was detected involving unauthorized access to the customer database containing personal data of registered users.'), styles['DPDPBody']))
            story.append(Spacer(1, 12))
            story.append(Paragraph("<b>Steps Taken:</b>", styles['DPDPBody']))
            steps = incident.get('steps', ['Identified breach vector', 'Contained the breach', 'Notified affected users', 'Initiated forensic audit'])
            for i, step in enumerate(steps, 1):
                story.append(Paragraph(f"{i}. {step}", styles['DPDPBody']))
            story += build_footer(styles)
            return story
        return self._generate(filename, build)

    def generate_customer_breach_notice(self, incident, customer=None):
        filename = f"customer_breach_notice_{incident.get('incident_id','')}.pdf"
        def build(styles):
            story = build_header(styles, "CUSTOMER BREACH NOTIFICATION", "Important Information About Your Data Security")
            story.append(Paragraph("Dear Valued Customer,", styles['DPDPBody']))
            story.append(Spacer(1, 8))
            story.append(Paragraph("We are writing to inform you about a data security incident that may have affected your personal information.", styles['DPDPBody']))
            story.append(Spacer(1, 12))
            story.append(build_info_table([
                ("Incident Date", incident.get('discovery_time', 'N/A')),
                ("What Happened", incident.get('nature', 'Unauthorized access detected')),
                ("Data Involved", incident.get('categories', 'Name, Email, Phone')),
                ("What We Did", "Immediate containment and security review"),
                ("What You Should Do", "Monitor accounts, change passwords, report suspicious activity"),
            ], styles))
            story.append(Spacer(1, 16))
            story.append(Paragraph("<b>Your Rights Under DPDP Act 2023:</b>", styles['DPDPBody']))
            rights = ['Right to access your personal data', 'Right to correction of inaccurate data', 'Right to erasure of personal data', 'Right to grievance redressal']
            for r in rights:
                story.append(Paragraph(f"  - {r}", styles['DPDPBody']))
            story += build_footer(styles)
            return story
        return self._generate(filename, build)

    def generate_audit_report(self, incident, timeline_events=None):
        filename = f"audit_report_{incident.get('incident_id','')}.pdf"
        def build(styles):
            story = build_header(styles, "INCIDENT AUDIT REPORT", f"Incident: {incident.get('incident_id', 'N/A')}")
            story.append(build_info_table([
                ("Incident ID", incident.get('incident_id', 'N/A')),
                ("Discovery Time", incident.get('discovery_time', 'N/A')),
                ("Closure Time", incident.get('closure_time', 'N/A')),
                ("Total Duration", incident.get('duration', 'N/A')),
                ("Severity", incident.get('severity', 'HIGH')),
                ("Attack Vector", incident.get('vector', 'Under Investigation')),
                ("Affected Records", incident.get('affected_count', 'N/A')),
            ], styles))
            story.append(Spacer(1, 16))
            story.append(Paragraph("<b>Timeline of Events:</b>", styles['DPDPBody']))
            story.append(Spacer(1, 8))
            events = timeline_events or [
                {"time": incident.get('discovery_time', 'N/A'), "event": "Breach discovered"},
                {"time": "T+15min", "event": "Incident response team activated"},
                {"time": "T+30min", "event": "Breach contained"},
                {"time": "T+1hr", "event": "DPB notification sent"},
                {"time": "T+2hr", "event": "Customer notifications sent"},
                {"time": "T+24hr", "event": "Forensic audit completed"},
            ]
            tdata = [["Time", "Event"]]
            for ev in events:
                tdata.append([ev['time'], ev['event']])
            t = Table(tdata, colWidths=[2*inch, 4.5*inch])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), BRAND_BLUE),
                ('TEXTCOLOR', (0,0), (-1,0), TEXT_WHITE),
                ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
                ('FONTSIZE', (0,0), (-1,-1), 9),
                ('TOPPADDING', (0,0), (-1,-1), 6),
                ('BOTTOMPADDING', (0,0), (-1,-1), 6),
                ('LINEBELOW', (0,0), (-1,-1), 0.5, colors.HexColor('#E5E7EB')),
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ]))
            story.append(t)
            story += build_footer(styles)
            return story
        return self._generate(filename, build)

    def generate_data_export(self, customer):
        cid = customer.get('customer_id', 'unknown')
        filename = f"data_export_{cid}.pdf"
        def build(styles):
            story = build_header(styles, "PERSONAL DATA EXPORT", f"Customer: {cid}")
            story.append(Paragraph("This document contains all personal data held by our organization for the requested customer, as per Section 11 of the DPDP Act, 2023.", styles['DPDPBody']))
            story.append(Spacer(1, 12))
            story.append(build_info_table([
                ("Customer ID", customer.get('customer_id', 'N/A')),
                ("Full Name", customer.get('name', 'N/A')),
                ("Email Address", customer.get('email', 'N/A')),
                ("Phone Number", customer.get('phone', 'N/A')),
                ("Account Status", customer.get('status', 'N/A')),
                ("Created At", customer.get('created_at', 'N/A')),
                ("Last Updated", customer.get('updated_at', 'N/A')),
            ], styles))
            story += build_footer(styles)
            return story
        return self._generate(filename, build)

    def generate_deletion_certificate(self, customer_id, deleted_fields):
        filename = f"deletion_cert_{customer_id}.pdf"
        def build(styles):
            story = build_header(styles, "DATA DELETION CERTIFICATE", f"Customer: {customer_id}")
            story.append(Paragraph("This certifies that the personal data of the below customer has been deleted/masked from our systems as per their request under the DPDP Act, 2023.", styles['DPDPBody']))
            story.append(Spacer(1, 12))
            story.append(build_info_table([
                ("Customer ID", customer_id),
                ("Deletion Date", datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')),
                ("Fields Deleted/Masked", ', '.join(deleted_fields)),
                ("Retention", "Customer ID retained for audit purposes"),
                ("Status", "COMPLETED"),
            ], styles))
            story += build_footer(styles)
            return story
        return self._generate(filename, build)

    def generate_correction_confirmation(self, customer_id, before, after):
        filename = f"correction_confirm_{customer_id}.pdf"
        def build(styles):
            story = build_header(styles, "DATA CORRECTION CONFIRMATION", f"Customer: {customer_id}")
            story.append(Paragraph("This confirms that the personal data has been corrected as requested under Section 12 of the DPDP Act, 2023.", styles['DPDPBody']))
            story.append(Spacer(1, 12))
            tdata = [["Field", "Before", "After"]]
            for field in before:
                if before.get(field) != after.get(field):
                    tdata.append([field.title(), str(before.get(field, '')), str(after.get(field, ''))])
            if len(tdata) == 1:
                tdata.append(["No changes", "-", "-"])
            t = Table(tdata, colWidths=[1.5*inch, 2.5*inch, 2.5*inch])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), BRAND_BLUE),
                ('TEXTCOLOR', (0,0), (-1,0), TEXT_WHITE),
                ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
                ('FONTSIZE', (0,0), (-1,-1), 9),
                ('TOPPADDING', (0,0), (-1,-1), 6),
                ('BOTTOMPADDING', (0,0), (-1,-1), 6),
                ('LINEBELOW', (0,0), (-1,-1), 0.5, colors.HexColor('#E5E7EB')),
            ]))
            story.append(t)
            story += build_footer(styles)
            return story
        return self._generate(filename, build)

    def generate_vector_analysis(self, analysis):
        filename = f"vector_analysis_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.pdf"
        def build(styles):
            story = build_header(styles, "ATTACK VECTOR ANALYSIS REPORT", "Security Assessment")
            story.append(build_info_table([
                ("Analysis Date", datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')),
                ("Likely Source", analysis.get('likely_source', 'Unknown')),
                ("Confidence", analysis.get('confidence', 'N/A')),
                ("API Status", analysis.get('api_status', 'N/A')),
                ("Email Status", analysis.get('email_status', 'N/A')),
            ], styles))
            story.append(Spacer(1, 16))
            story.append(Paragraph("<b>API Security Signals:</b>", styles['DPDPBody']))
            for s in analysis.get('api_signals', []):
                icon = "PASS" if s.get('ok') else "FAIL"
                story.append(Paragraph(f"  [{icon}] {s.get('label', '')}", styles['DPDPBody']))
            story.append(Spacer(1, 12))
            story.append(Paragraph("<b>Email Security Signals:</b>", styles['DPDPBody']))
            for s in analysis.get('email_signals', []):
                icon = "PASS" if s.get('ok') else "FAIL"
                story.append(Paragraph(f"  [{icon}] {s.get('label', '')}", styles['DPDPBody']))
            story.append(Spacer(1, 12))
            story.append(Paragraph("<b>Key Findings:</b>", styles['DPDPBody']))
            for f in analysis.get('findings', ['No anomalies detected']):
                story.append(Paragraph(f"  - {f}", styles['DPDPBody']))
            story += build_footer(styles)
            return story
        return self._generate(filename, build)
